{{- if .Values.app.image.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: gcr-json-key
  labels:
    app: {{ .Values.app.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.app.image.imagePullSecret }}
{{- end }}










