apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  dbPassword: {{ .Values.postgresql.auth.password | quote }}
  {{- if .Values.redis.auth.enabled }}
  redisPassword: {{ .Values.redis.auth.password | quote }}
  {{- end }}

